page_config:
  page_title: "SaveGlass"
  page_icon: "🔍"
  layout: "wide"
  initial_sidebar_state: "expanded"

theme:
  light:
    primary_color: "#251B9C"
    secondary_color: "#7059FF"
    background_color: "#ffffff"
    text_color: "#2D2D2D"
  dark:
    primary_color: "#7059FF"
    secondary_color: "#ADA6FF"
    background_color: "#1E1E1E"
    text_color: "#E0E0E0"

chat_styling:
  light:
    user_message:
      background_color: "#F8F7FF"
      border_color: "#251B9C"
      border_width: "4px"
    assistant_message:
      background_color: "#C7C2FF"
      border_color: "#7059FF"
      border_width: "4px"
  dark:
    user_message:
      background_color: "#2D2B4A"
      border_color: "#7059FF"
      border_width: "4px"
    assistant_message:
      background_color: "#3A3556"
      border_color: "#ADA6FF"
      border_width: "4px"
  message_padding: "1rem"
  message_border_radius: "0.5rem"
  message_margin_bottom: "1rem"
  input_border_radius: "20px"

sidebar:
  title: "🔧 Configuration"
  sections:
    agent_settings:
      title: "Agent Settings"
      show_model_selector: true
      show_temperature_slider: true
      show_max_tokens_input: true
    provider_settings:
      title: "Provider Settings"
      show_provider_selector: true
      show_api_status: true
    chat_controls:
      show_clear_button: true
      clear_button_text: "Clear Chat History"
      update_button_text: "Update Agent Config"

messages:
  welcome_message: "Welcome to SaveGlass! Ask questions about your AWS costs, request data analysis, or generate plots."
  thinking_spinner: "Thinking..."
  error_prefix: "Error: "
  success_config_update: "Agent configuration updated!"
  warning_no_credentials: "API credentials not configured. Please set the appropriate environment variables."

input_placeholder: "Ask me anything about your AWS costs... (try: 'Which service cost me the most last month?' or 'analyze cost trends')"

example_questions:
  enabled: true
  title: "💡 Example Questions"
  questions:
    - text: "Which service cost me the most last month?"
      description: "Analyses customer data to identify the most expensive service"
    - text: "Analyze customer data trends"  
      description: "Provides insights on customer behavior patterns"
    - text: "What are the key benefits of AI in business?"
      description: "Discusses AI applications in business contexts"

visualization:
  chart_keywords: ["chart", "plot", "graph", "visualiz"]
  use_container_width: true
  default_theme: "plotly"